"""Git履歴・co-author・remoteをmaterializeする。"""

from __future__ import annotations

from dataclasses import dataclass, field
import re
from typing import Callable, Sequence

from agentscope.acquisition.artifacts import ArtifactStore
from agentscope.acquisition.git_snapshot import AcquisitionError, Snapshot, run_git
from agentscope.analysis.evidence_helpers import add_hit_evidence
from agentscope.analysis.search import SearchHit
from agentscope.domain.evidence import EvidenceLedger


@dataclass
class ProvenanceFacts:
    available: bool
    ai_signals: list[str] = field(default_factory=list)
    weak_ai_signals: list[str] = field(default_factory=list)
    remotes: list[str] = field(default_factory=list)
    coverage: str = "partial"
    evidence_ids: list[str] = field(default_factory=list)


_AI_RE = re.compile(
    r"(co-authored-by|coauthored|claude|copilot|chatgpt|openai|anthropic|gemini|cursor|codeium|"
    r"generated by ai|ai-assisted)",
    re.IGNORECASE,
)


def inspect_git_provenance(
    snapshot: Snapshot,
    artifacts: ArtifactStore,
    ledger: EvidenceLedger,
    *,
    commit_sha: str,
    runner: Callable[..., object] = run_git,
) -> ProvenanceFacts:
    facts = ProvenanceFacts(available=False, coverage="partial")
    log_text = ""
    remote_text = ""
    try:
        log_result = runner(
            [
                "git",
                "log",
                "-n",
                "200",
                "--format=commit=%H%nAuthor=%an <%ae>%nCommitter=%cn <%ce>%n%B%n---",
            ],
            cwd=snapshot.root,
            timeout=60,
        )
        if getattr(log_result, "returncode", 1) == 0:
            log_text = getattr(log_result, "stdout", "")
            facts.available = True
        else:
            log_text = getattr(log_result, "stderr", "") or "git log failed"
    except (AcquisitionError, OSError) as exc:
        log_text = f"git log unavailable: {exc}"
    try:
        remote_result = runner(
            ["git", "remote", "-v"],
            cwd=snapshot.root,
            timeout=30,
        )
        if getattr(remote_result, "returncode", 1) == 0:
            remote_text = getattr(remote_result, "stdout", "")
            facts.remotes = [
                line.split()[1]
                for line in remote_text.splitlines()
                if len(line.split()) >= 2
            ]
        else:
            remote_text = getattr(remote_result, "stderr", "") or "git remote failed"
    except (AcquisitionError, OSError) as exc:
        remote_text = f"git remotes unavailable: {exc}"

    if not log_text.strip():
        log_text = "git log unavailable\n"
    if not remote_text.strip():
        remote_text = "git remotes unavailable\n"

    artifacts.write_text("provenance/git-log.txt", log_text)
    artifacts.write_text("provenance/git-remotes.txt", remote_text)
    lines = log_text.splitlines()
    signal_lines: list[SearchHit] = []
    for line_no, line in enumerate(lines, 1):
        if _AI_RE.search(line):
            signal_lines.append(SearchHit("provenance/git-log.txt", line_no, line[:1000]))
    for hit in signal_lines:
        evidence = add_hit_evidence(
            ledger,
            hit,
            claim_key="provenance.ai_assisted",
            commit_sha=commit_sha,
            reason="Git provenance contains an explicit AI assistance signal.",
            confidence="medium",
            source_kind="git",
        )
        facts.ai_signals.append(hit.text)
        facts.evidence_ids.append(evidence.id)

    if not facts.ai_signals:
        for line_no, line in enumerate(lines, 1):
            if re.search(r"author=|committer=", line, re.IGNORECASE):
                hit = SearchHit("provenance/git-log.txt", line_no, line[:1000])
                evidence = add_hit_evidence(
                    ledger,
                    hit,
                    claim_key="provenance.ai_assisted.coverage",
                    commit_sha=commit_sha,
                    reason="Bounded Git provenance was inspected; no explicit AI co-author was found.",
                    confidence="low" if facts.available else "unknown",
                    source_kind="git",
                )
                facts.evidence_ids.append(evidence.id)
                break
        else:
            evidence = ledger.add(
                claim_key="provenance.ai_assisted.coverage",
                source_kind="derived_manifest",
                file="provenance/git-log.txt",
                start_line=1,
                end_line=1,
                excerpt=log_text.splitlines()[0] if log_text.splitlines() else "git log unavailable",
                commit_sha=commit_sha,
                reason="Git provenance could not provide an explicit co-author signal.",
                confidence="unknown",
            )
            facts.evidence_ids.append(evidence.id)

    if facts.remotes:
        remote_lines = remote_text.splitlines()
        evidence = add_hit_evidence(
            ledger,
            SearchHit("provenance/git-remotes.txt", 1, remote_lines[0][:1000]),
            claim_key="provenance.remotes",
            commit_sha=commit_sha,
            reason="Git remote metadata was inspected; remote similarity is not a formal fork proof.",
            confidence="medium",
            source_kind="git",
        )
        facts.evidence_ids.append(evidence.id)
    facts.coverage = "full" if facts.available else "partial"
    return facts
